### ISSUE TITLE
Problem about simply replace nn.Module.ReLU() with GuidedBackpropReLU.apply

### ISSUE THREAD

**Issue by XYPB** [jacobgil/pytorch-grad-cam#111]
## Bug:
```bash
Traceback (most recent call last):
  File "extract_feature.py", line 264, in <module>
    main(args)
  File "extract_feature.py", line 244, in main
    get_cam(net, trans, args)
  File "extract_feature.py", line 128, in get_cam
    gb = gb_model(x, target_category=d)
  File "/usr/local/lib/python3.6/site-packages/pytorch_grad_cam/guided_backprop.py", line 63, in __call__
    output = self.forward(input_img)
  File "/usr/local/lib/python3.6/site-packages/pytorch_grad_cam/guided_backprop.py", line 36, in forward
    return self.model(input_img)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 151, in forward
    for t in chain(self.module.parameters(), self.module.buffers()):
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1089, in parameters
    for name, param in self.named_parameters(recurse=recurse):
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1115, in named_parameters
    for elem in gen:
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1059, in _named_members
    for module_prefix, module in modules:
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1257, in named_modules
    for m in module.named_modules(memo, submodule_prefix):
  File "/usr/local/lib64/python3.6/site-packages/torch/nn/modules/module.py", line 1257, in named_modules
    for m in module.named_modules(memo, submodule_prefix):
AttributeError: 'builtin_function_or_method' object has no attribute 'named_modules'
```

### Env:
Ubuntu on docker with cuda 10.1, pytorch 1.7.0
### Details:
I was trying to get the guided backpropagate map for a MoCo model, with resnet50 as its backbone, and used DataParallel for multi-GPU training. And the error occurs when I was calling the forward of `GuidedBackpropReLUModel`. And the `cam.py` example works perfectly so I am assuming it is not the problem of the environment or other settings.

### Possible Reason
It seems that the reason for this error is that the data-parallel model is trying to iterate over all its children modules, and for the original MoCo model, it uses `nn.Module.ReLU()`, which is an `nn.Module` object. However, when `GuidedBackpropReLUModel` is replacing the ReLU modules inside the model, it uses `GuidedBackpropReLU.apply`, which is of the type `builtin_function_or_method`, and it will fail during the recursion inside the data-parallel model since it does not have any attributes that `nn.Module` should have.

### My Solution
A possible solution is to replace create a guided backpropagate module of nn.Module class, which directly call the `GuidedBackpropReLU` function:
```python
class GuidedBackpropReLUasModule(nn.Module):
    def __init__(self):
        super(GuidedBackpropReLUasModule, self).__init__()

    def forward(self, input_img):
        return GuidedBackpropReLU.apply(input_img)
```
and replace `GuidedBackpropReLU.apply` in `recursive_replace_relu_with_guidedrelu` and `recursive_replace_guidedrelu_with_relu` with an instance of this object:
```python
def recursive_replace_relu_with_guidedrelu(self, module_top):
    ...
    module_top._modules[idx] = GuidedBackpropReLUasModule()
    ...

def recursive_replace_guidedrelu_with_relu(self, module_top):
    ...
    if module.__class__.__name__ == 'GuidedBackpropReLUasModule':
    ...
```
Not very sure about the correctness, but it solves my problem. Hope this can be helpful if someone met the same problem.

**Comment by wendy-lei2** [comment]
Thank you very much. Your answer has solved my problem

**Comment by jacobgil** [comment]
This is great, thanks.
Merged into the master branch.
