### ISSUE TITLE
TypeError: __init__() got an unexpected keyword argument 'target_layer'

### ISSUE THREAD

**Issue by prinzROSE** [jacobgil/pytorch-grad-cam#176]
Exception ignored in: <bound method BaseCAM.__del__ of <pytorch_grad_cam.grad_cam.GradCAM object at 0x7fc75494ac88>>
Traceback (most recent call last):
  File "/data/caiyong.wang/bin/anaconda3/envs/gu1/lib/python3.6/site-packages/pytorch_grad_cam/base_cam.py", line 192, in __del__
    self.activations_and_grads.release()
AttributeError: 'GradCAM' object has no attribute 'activations_and_grads'
Traceback (most recent call last):
  File "/data1/caiyong.wang/song/original_DeepCrack/codes/heat map.py", line 56, in <module>
    cam = GradCAM(model=model, target_layer=target_layer, use_cuda=False)
TypeError: __init__() got an unexpected keyword argument 'target_layer'

hi,I have a problem. please u help me!thank u

**Comment by wxr5899** [comment]
I guess you just spell the attribute wrong, it should be `target_layers` not `target_layer`. This will lead to the defeat of the initialization of attribute `activations_and_grads`. Hope this can help you!

**Comment by jacobgil** [comment]
Yes, it should be target_layers (and it should be a list).

**Comment by xzk18360175140** [comment]
(py310) D:\cmi_china\agile_innovation\agile_innovation\backend>flask run
 * Serving Flask app "agile/app"
 * Environment: rc
 * Debug mode: off
Traceback (most recent call last):
  File "D:\Miniconda\envs\py310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\Miniconda\envs\py310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "D:\Miniconda\envs\py310\Scripts\flask.exe\__main__.py", line 7, in <module>        
  File "D:\Miniconda\envs\py310\lib\site-packages\flask\cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)        
  File "D:\Miniconda\envs\py310\lib\site-packages\flask\cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "D:\Miniconda\envs\py310\lib\site-packages\click\core.py", line 782, in main        
    rv = self.invoke(ctx)
  File "D:\Miniconda\envs\py310\lib\site-packages\click\core.py", line 1259, in invoke     
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Miniconda\envs\py310\lib\site-packages\click\core.py", line 1066, in invoke     
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Miniconda\envs\py310\lib\site-packages\click\core.py", line 610, in invoke      
    return callback(*args, **kwargs)
  File "D:\Miniconda\envs\py310\lib\site-packages\click\decorators.py", line 73, in new_func
    return ctx.invoke(f, obj, *args, **kwargs)
  File "D:\Miniconda\envs\py310\lib\site-packages\click\core.py", line 610, in invoke      
    return callback(*args, **kwargs)
  File "D:\Miniconda\envs\py310\lib\site-packages\flask\cli.py", line 848, in run_command  
    app = DispatchingApp(info.load_app, use_eager_loading=eager_loading)
  File "D:\Miniconda\envs\py310\lib\site-packages\flask\cli.py", line 305, in __init__     
    self._load_unlocked()
  File "D:\Miniconda\envs\py310\lib\site-packages\flask\cli.py", line 330, in _load_unlocked
    self._app = rv = self.loader()
  File "D:\Miniconda\envs\py310\lib\site-packages\flask\cli.py", line 388, in load_app     
    app = locate_app(self, import_name, name)
  File "D:\Miniconda\envs\py310\lib\site-packages\flask\cli.py", line 240, in locate_app   
    __import__(module_name)
  File "D:\cmi_china\agile_innovation\agile_innovation\backend\agile\app.py", line 7, in <module>
    from agile import auth, api, commands
  File "D:\cmi_china\agile_innovation\agile_innovation\backend\agile\auth\__init__.py", line 1, in <module>
    from . import views
  File "D:\cmi_china\agile_innovation\agile_innovation\backend\agile\auth\views.py", line 16, in <module>
    from agile.models import User
  File "D:\cmi_china\agile_innovation\agile_innovation\backend\agile\models\__init__.py", line 7, in <module>
    from .category import Category
  File "D:\cmi_china\agile_innovation\agile_innovation\backend\agile\models\category.py", line 26, in <module>
    class Category(AuditModel):
  File "D:\Miniconda\envs\py310\lib\site-packages\flask_sqlalchemy\model.py", line 67, in __init__
    super(NameMetaMixin, cls).__init__(name, bases, d)
n __init__    self._early_mapping(mapper_kw)
  File "D:\Miniconda\envs\py310\lib\site-packages\sqlalchemy\orm\decl_base.py", line 215, in _early_mapping    self.map(mapper_kw)
  File "D:\Miniconda\envs\py310\lib\site-packages\sqlalchemy\orm\decl_base.py", line 1013, in map    mapper_cls(self.cls, self.local_table, **self.mapper_args),
TypeError: Mapper.__init__() got an unexpected keyword argument 'order_by'

**Comment by wxr5899** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
