### ISSUE TITLE
Problem with inception

### ISSUE THREAD

**Issue by midya2020** [jacobgil/pytorch-grad-cam#205]
I tried with resnet and densenet and worked fine. But faced difficulties with inception v3. Can you please suggest how to implement this in inception v3?
 model = torch.load(ModelName)
 model.eval()
target_layers = model._modules.get('Mixed_7c')
cam = GradCAM(model=model, target_layers=target_layers, use_cuda=True)
But got following error. Can you please help me in fixing the issue or suuggest any changes.

C:\ProgramData\Anaconda3\envs\DeepLearning2\python.exe C:/Abhishek/Research/LiverClassification/ActivationLayer.py
Traceback (most recent call last):
  File "C:/Research/LiverClassification/ActivationLayer.py", line 60, in <module>
    cam = GradCAM(model=model, target_layers=target_layers, use_cuda=True)
  File "C:\ProgramData\Anaconda3\envs\DeepLearning2\lib\site-packages\pytorch_grad_cam\grad_cam.py", line 8, in __init__
    super(
  File "C:\ProgramData\Anaconda3\envs\DeepLearning2\lib\site-packages\pytorch_grad_cam\base_cam.py", line 27, in __init__
    self.activations_and_grads = ActivationsAndGradients(
  File "C:\ProgramData\Anaconda3\envs\DeepLearning2\lib\site-packages\pytorch_grad_cam\activations_and_gradients.py", line 11, in __init__
    for target_layer in target_layers:
TypeError: 'InceptionE' object is not iterable
Exception ignored in: <function BaseCAM.__del__ at 0x000001F62F615DC0>
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\DeepLearning2\lib\site-packages\pytorch_grad_cam\base_cam.py", line 188, in __del__
    self.activations_and_grads.release()
AttributeError: 'GradCAM' object has no attribute 'activations_and_grads'

**Comment by jacobgil** [comment]
Hi, target_layers should be a list.
Can you please try target_layers = [model._modules.get('Mixed_7c')] ?

**Comment by midya2020** [comment]
Thank you so much
