### ISSUE TITLE
RuntimeError: [enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory

### ISSUE THREAD

**Issue by chenxinhe1** [jacobgil/pytorch-grad-cam#291]
(swin-t) cxh@cxh-OMEN-by-HP-Laptop-17-cb1xxx:~/pytorch-grad-cam-master(1)$ python swinT_example.py --image-path ./image/1.jpg --use-cuda
/home/cxh/anaconda3/envs/swin-t/lib/python3.7/site-packages/apex-0.1-py3.7.egg/apex/pyprof/__init__.py:5: FutureWarning: pyprof will be removed by the end of June, 2022
  warnings.warn("pyprof will be removed by the end of June, 2022", FutureWarning)
Using GPU for acceleration
Traceback (most recent call last):
  File "swinT_example.py", line 85, in <module>
    model = timm.create_model('swin_base_patch4_window7_224', pretrained=True)
  File "/home/cxh/anaconda3/envs/swin-t/lib/python3.7/site-packages/timm/models/factory.py", line 74, in create_model
    model = create_fn(pretrained=pretrained, **kwargs)
  File "/home/cxh/anaconda3/envs/swin-t/lib/python3.7/site-packages/timm/models/swin_transformer.py", line 585, in swin_base_patch4_window7_224
    return _create_swin_transformer('swin_base_patch4_window7_224', pretrained=pretrained, **model_kwargs)
  File "/home/cxh/anaconda3/envs/swin-t/lib/python3.7/site-packages/timm/models/swin_transformer.py", line 564, in _create_swin_transformer
    **kwargs)
  File "/home/cxh/anaconda3/envs/swin-t/lib/python3.7/site-packages/timm/models/helpers.py", line 470, in build_model_with_cfg
    strict=pretrained_strict)
  File "/home/cxh/anaconda3/envs/swin-t/lib/python3.7/site-packages/timm/models/helpers.py", line 189, in load_pretrained
    state_dict = load_state_dict_from_url(pretrained_url, progress=progress, map_location='cpu')
  File "/home/cxh/anaconda3/envs/swin-t/lib/python3.7/site-packages/torch/hub.py", line 495, in load_state_dict_from_url
    return torch.load(cached_file, map_location=map_location)
  File "/home/cxh/anaconda3/envs/swin-t/lib/python3.7/site-packages/torch/serialization.py", line 577, in load
    with _open_zipfile_reader(opened_file) as opened_zipfile:
  File "/home/cxh/anaconda3/envs/swin-t/lib/python3.7/site-packages/torch/serialization.py", line 241, in __init__
    super(_open_zipfile_reader, self).__init__(torch._C.PyTorchFileReader(name_or_buffer))
RuntimeError: [enforce fail at inline_container.cc:144] . PytorchStreamReader failed reading zip archive: failed finding central directory
when i run swinT.example.py,there is a error,how to deal with it?thanks

**Comment by jacobgil** [comment]
Hi, this seems related to the timm package or with the internet connection, unfortunately can't help with it.
Maybe there was a temporary unavailability.
