### ISSUE TITLE
Can not visualize image via show_cam_on_image

### ISSUE THREAD

**Issue by Waterkin** [jacobgil/pytorch-grad-cam#365]
To replicate error:
```
target_layers = [
        model.layer4[-1]
    ]  # last layer before classfier
cam = GradCAM(model=model, target_layers=target_layers, use_cuda=True)
transform_test = transforms.Compose(
        [
            transforms.ToTensor(),
            transforms.Normalize((0.4914, 0.4822, 0.4465), (0.2023, 0.1994, 0.2010)),
        ]
    )
test_set = CIFAR10(
        root="./data",
        train=False,
        download=True,
        transform=transform_test,
    )
eva_loader = DataLoader(
        dataset=test_set,
        batch_size=256,
        shuffle=False,
        num_workers=8,
        pin_memory=True,  # 256
    )
for i, (images, labels) in enumerate(eva_loader):
        print(images.shape, labels.shape) # output: torch.Size([256, 3, 32, 32]) torch.Size([256])
        img = Variable(images).cuda()
        targets = None
        cam.batch_size = 256
        grayscale_cam = cam(input_tensor=img, targets=targets)
        print(grayscale_cam.shape) # output: (256, 32, 32)
        grayscale_cam = grayscale_cam[0, :]
        visualization = show_cam_on_image(
            images[0, :, :, :], grayscale_cam, use_rgb=True
        )
```

Error message:
```
Traceback (most recent call last):
  File "gradcam.py", line 117, in <module>
    gradcam()
  File "gradcam.py", line 107, in gradcam
    visualization = show_cam_on_image(
  File "python3.8/site-packages/pytorch_grad_cam/utils/image.py", line 53, in show_cam_on_image
    if np.max(img) > 1:
  File "<__array_function__ internals>", line 180, in amax
  File "python3.8/site-packages/numpy/core/fromnumeric.py", line 2793, in amax
    return _wrapreduction(a, np.maximum, 'max', axis, None, out,
  File "python3.8/site-packages/numpy/core/fromnumeric.py", line 84, in _wrapreduction
    return reduction(axis=axis, out=out, **passkwargs)
TypeError: max() received an invalid combination of arguments - got (out=NoneType, axis=NoneType, ), but expected one of:
 * ()
 * (name dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis
 * (Tensor other)
 * (int dim, bool keepdim)
      didn't match because some of the keywords were incorrect: out, axis
```

**Comment by taomanwai** [comment]
Same here. Even there's no transforms.Normalize(), same error still exists.

Anyone has comments ?

**Comment by AdrianIordache** [comment]
Accidentally I reproduced your problem today, after looking at the source code in my env, I saw that this is caused by the fact that you pass to "show_cam_on_image" as the first argument a tensor (images[0, :, :, :]) instead of a np.array()

**Comment by jacobgil** [comment]
Hi all,
show_cam_on_image expects a numpy image with the format rows x cols x 3.
In the code above, images[0, :, :, :] is a pytorch tensor with the shape 3 x rows x cols.
