### ISSUE TITLE
'tuple' object has no attribute 'cpu'

### ISSUE THREAD

**Issue by sumit-iitp-2111** [jacobgil/pytorch-grad-cam#386]
when I try to execute grayscale_cam = cam(tensor)[0, :,:] in the tutorial for yolov5, I get this error. Please help, I am using the same code for yolov7

**Comment by CAkahay** [comment]
Please let me know how we can resolve this problem if ur done with this problem

**Comment by jacobgil** [comment]
It is possible that the YOLO5 model changed and now also returns something else.
The tutorial assumed that the YOLO5 model returns a tensor, when it gets a tensor.

I need to check what it returns now (i'm outside right now so can't check that yet),
but if we know that it returns for example a tuple where the first element is the actual tensor,
we could wrap it in a model that gets the first element.

```python
class YOLOModelOutputWrapper(torch.nn.Module):
    def __init__(self, model): 
        super(YOLOModelOutputWrapper, self).__init__()
        self.model = model
        
    def forward(self, x):
        return self.model(x)[0]
    
model = YOLOModelOutputWrapper(model)
```

Can someone please confirm what YOLO returns now?

**Comment by acsgn95** [comment]
@sumit-iitp-2111 you need to go BaseCAM and you must to put there an if condition!

**Comment by acsgn95** [comment]
@JunKaiLiao can you share the total error to here? I will help

**Comment by JunKaiLiao** [comment]
Hi, @acsgn95 Thanks for your reply!!  I got the error as shown below. 

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Input In [55], in <cell line: 4>()
      2 boxes, colors, names = parse_detections(results)
      3 cam = EigenCAM(model, target_layers, use_cuda=False)
----> 4 grayscale_cam = cam(tensor)[0, :, :]
      5 cam_image = show_cam_on_image(img, grayscale_cam, use_rgb=True)
      6 Image.fromarray(cam_image)

File ~/JunKai/yolov7_Cam/pytorch_grad_cam/base_cam.py:188, in BaseCAM.__call__(self, input_tensor, targets, aug_smooth, eigen_smooth)
    184 if aug_smooth is True:
    185     return self.forward_augmentation_smoothing(
    186         input_tensor, targets, eigen_smooth)
--> 188 return self.forward(input_tensor,
    189                     targets, eigen_smooth)

File ~/JunKai/yolov7_Cam/pytorch_grad_cam/base_cam.py:76, in BaseCAM.forward(self, input_tensor, targets, eigen_smooth)
     74 outputs = self.activations_and_grads(input_tensor)
     75 if targets is None:
---> 76     target_categories = np.argmax(outputs.cpu().data.numpy(), axis=-1)
     77     targets = [ClassifierOutputTarget(
     78         category) for category in target_categories]
     80 if self.uses_gradients:

AttributeError: 'tuple' object has no attribute 'cpu'

**Comment by fallcat** [comment]
@acsgn95 I have the same problem with ViT. I tried the above wrapping method but it doesn't work. Could you help me take a look? Thanks!

```
class WrappedModel(torch.nn.Module):
    def __init__(self, model, postprocess): 
        super(WrappedModel, self).__init__()
        self.model = model
        self.postprocess = postprocess
        
    def forward(self, x):
        return self.model(x)[0]

class TorchImageGradCAM(TorchAttribution):
    def __init__(self, model, target_layer, postprocess=None):
        model = WrappedModel(model, postprocess)

        super().__init__(model, postprocess)
        
        self.target_layer = target_layer
        self.grad_cam = GradCAM(model=model, target_layers=[model.model.vit.encoder.layer[11]], 
                                use_cuda=True if torch.cuda.is_available() else False)
        

    def forward(self, X, label=None):
        grad_cam_result = self.grad_cam(input_tensor=X)
        return grad_cam_result


```

And trace back

```
Traceback (most recent call last):                                             | 0/3 [00:00<?, ?it/s]
  File "actions/wrapper/eval_wrapper_cls_explainers.py", line 458, in <module>
    main()
  File "actions/wrapper/eval_wrapper_cls_explainers.py", line 384, in main
    expln = explainer(inputs)
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nlp/data/weiqiuy/exlib/src/exlib/explainers/gradcam.py", line 38, in forward
    grad_cam_result = self.grad_cam(input_tensor=X)
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 188, in __call__
    return self.forward(input_tensor,
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/pytorch_grad_cam/base_cam.py", line 74, in forward
    outputs = self.activations_and_grads(input_tensor)
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/pytorch_grad_cam/activations_and_gradients.py", line 42, in __call__
    return self.model(x)
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nlp/data/weiqiuy/exlib/src/exlib/explainers/gradcam.py", line 15, in forward
    return self.model(x)[0]
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/transformers/models/vit/modeling_vit.py", line 787, in forward
    outputs = self.vit(
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/transformers/models/vit/modeling_vit.py", line 577, in forward
    encoder_outputs = self.encoder(
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1501, in _call_impl
    return forward_call(*args, **kwargs)
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/transformers/models/vit/modeling_vit.py", line 407, in forward
    layer_outputs = layer_module(hidden_states, layer_head_mask, output_attentions)
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1547, in _call_impl
    hook_result = hook(self, args, result)
  File "/nlp/data/weiqiuy/miniconda3/envs/attn/lib/python3.8/site-packages/pytorch_grad_cam/activations_and_gradients.py", line 24, in save_activation
    self.activations.append(activation.cpu().detach())
AttributeError: 'tuple' object has no attribute 'cpu'
```

**Comment by ymy1946676292** [comment]
To solve this problem，please follow the blow process:
Firstly, change this file, from this picture:
![first](https://github.com/jacobgil/pytorch-grad-cam/assets/77595767/305cd002-e9d2-41f2-ab7f-30dd1e6b8c0a)
Secondly, change this file, from this picture:
![second](https://github.com/jacobgil/pytorch-grad-cam/assets/77595767/babe77b8-22ea-4abd-94bf-f11aa99ee2c9)

**Comment by azizjadehs** [comment]
@ymy1946676292 @JunKaiLiao @jacobgil  Hello guys I hope you are doing well.

I am interested to know if you guys managed to use Grad-CAM with YOLOv7.
I am trying to do it since a week and I solved many problems, however I encounter a new problem every time I am solving something.

Now I got an error message  TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first. which refers to the tensor still being in the GPU and I tried to solve it with .cpu() but not working.

Any ideas ?

**Comment by ymy1946676292** [comment]
Hello, you can use Tensor.cpu().numpy() to have a try
---- Replied Message ----
From Abdulaziz ***@***.***> Date 07/30/2024 20:45 To ***@***.***> Cc ***@***.***>***@***.***> Subject Re: [jacobgil/pytorch-grad-cam] 'tuple' object has no attribute 'cpu' (Issue #386) 
@ymy1946676292 @JunKaiLiao @jacobgil Hello guys I hope you are doing well.
I am interested to know if you guys managed to use Grad-CAM with YOLOv7.
I am trying to do it since a week and I solved many problems, however I encounter a new problem every time I am solving something.
Now I got an error message TypeError: can't convert cuda:0 device type tensor to numpy. Use Tensor.cpu() to copy the tensor to host memory first. which refers to the tensor still being in the GPU and I tried to solve it with .cpu() but not working.
Any ideas ?

**Comment by ninadchobe** [comment]
@azizjadehs @ymy1946676292 were you able to use this for yolov7? I'm trying the same but aint getting anywhere

**Comment by azizjadehs** [comment]
@ninadchobe Hello Ninad I am sorry for the late answer. 

Yes I did manage to make a working code for YOLOv7 with Grad-CAM and Grad-CAM ++.
I will upload the code with all necessary adjustments.

**Comment by azizjadehs** [comment]
@ninadchobe Hi I uploaded the main code and the script to use Grad-CAM and Grad-CAM++ on YOLOv7 here:
https://github.com/azizjadehs/YOLOv7-to-be-used-on-Grad-CAM

It took me long, however at last it's solved.

**Comment by ninadchobe** [comment]
@azizjadehs thanks a lot for going through the trouble. But can you elaborate a bit more in the readme about the setup ? I really appreciate the help

**Comment by azizjadehs** [comment]
@ninadchobe I updated the repos and fixed some mistakes and made sure it will work now. I also uploaded a notebook tutorial for more clarification.
If there is any further troubles, feel free to ask.

**Comment by Muraam-Abdel-Ghani** [comment]
> To solve this problem，please follow the blew process: Firstly, change this file, from this picture: ![first](https://github.com/jacobgil/pytorch-grad-cam/assets/77595767/305cd002-e9d2-41f2-ab7f-30dd1e6b8c0a) Secondly, change this file, from this picture: ![second](https://github.com/jacobgil/pytorch-grad-cam/assets/77595767/babe77b8-22ea-4abd-94bf-f11aa99ee2c9)

Hi, I am also getting the same issue trying to run GradCAM for a Segformer model. I wrapped the model output as suggested, but I still get the same issue. I cannot change the files as suggested by the solution here because I am importing the library on cloud gpu and the libraries do not appear in the filesystem the way cloning the library locally does. 
This is the code I am using:
`class SegmentationModelOutputWrapper(torch.nn.Module):
    def __init__(self, model): 
        super(SegmentationModelOutputWrapper, self).__init__()
        self.model = model
        
    def forward(self, x):
        return self.model(x)["logits"]

def get_class_binary_mask(category_index, mask):
    category_mask = mask[0, :, :].argmax(axis=0).detach().cpu().numpy()
    # category_mask_uint8 = 255 * np.uint8(category_mask == category_index)
    category_mask_float = np.float32(category_mask == category_index)
    
    return category_mask_float

model = SegformerForSemanticSegmentation.from_pretrained('nvidia/mit-b5' ,  
                                                         id2label=id2label,
                                                        label2id=label2id,
                                                        num_labels=num_classes)
model.load_state_dict(torch.load("/notebooks/Orig_Segformer/models/segformer_model.pth"))
model = SegmentationModelOutputWrapper(model)
model.to(device)

target_layers = [model.model.segformer.encoder.block[0][2]]

pixel_values=input_tensor["pixel_values"].unsqueeze(0).to(device)
labels = input_tensor["labels"].unsqueeze(0).to(device)

outputs = model(pixel_values,labels)
logits_resized = F.interpolate(outputs.logits, size=labels.shape[1:], mode='bilinear', align_corners=False)
preds = torch.argmax(logits_resized, dim=1)

targets = [SemanticSegmentationTarget(category_name_to_index("instrument-shaft"),get_class_binary_mask(category_name_to_index("instrument-shaft"), preds.cpu()))] 


with GradCAM(model=model, target_layers=target_layers) as cam:
    grayscale_cam = cam(input_tensor=pixel_values.detach().cpu(), targets=targets)[0, :]
    # grayscale_cam = grayscale_cam[0, :]
    visualization = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)
    
    Image.fromarray(visualization)
`

This is the error:
`AttributeError                            Traceback (most recent call last)
Cell In[82], line 2
      1 with GradCAM(model=model, target_layers=target_layers) as cam:
----> 2     grayscale_cam = cam(input_tensor=pixel_values.detach().cpu(), targets=targets)[0, :]
      3     # grayscale_cam = grayscale_cam[0, :]
      4     visualization = show_cam_on_image(rgb_img, grayscale_cam, use_rgb=True)

File /usr/local/lib/python3.11/dist-packages/pytorch_grad_cam/base_cam.py:186, in BaseCAM.__call__(self, input_tensor, targets, aug_smooth, eigen_smooth)
    183 if aug_smooth is True:
    184     return self.forward_augmentation_smoothing(input_tensor, targets, eigen_smooth)
--> 186 return self.forward(input_tensor, targets, eigen_smooth)

File /usr/local/lib/python3.11/dist-packages/pytorch_grad_cam/base_cam.py:90, in BaseCAM.forward(self, input_tensor, targets, eigen_smooth)
     87 if self.compute_input_gradient:
     88     input_tensor = torch.autograd.Variable(input_tensor, requires_grad=True)
---> 90 self.outputs = outputs = self.activations_and_grads(input_tensor)
     92 if targets is None:
     93     target_categories = np.argmax(outputs.cpu().data.numpy(), axis=-1)

File /usr/local/lib/python3.11/dist-packages/pytorch_grad_cam/activations_and_gradients.py:42, in ActivationsAndGradients.__call__(self, x)
     40 self.gradients = []
     41 self.activations = []
---> 42 return self.model(x)

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

Cell In[73], line 7, in SegmentationModelOutputWrapper.forward(self, x)
      6 def forward(self, x):
----> 7     return self.model(x)["logits"]

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local/lib/python3.11/dist-packages/transformers/models/segformer/modeling_segformer.py:793, in SegformerForSemanticSegmentation.forward(self, pixel_values, labels, output_attentions, output_hidden_states, return_dict)
    788 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
    789 output_hidden_states = (
    790     output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
    791 )
--> 793 outputs = self.segformer(
    794     pixel_values,
    795     output_attentions=output_attentions,
    796     output_hidden_states=True,  # we need the intermediate hidden states
    797     return_dict=return_dict,
    798 )
    800 encoder_hidden_states = outputs.hidden_states if return_dict else outputs[1]
    802 logits = self.decode_head(encoder_hidden_states)

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local/lib/python3.11/dist-packages/transformers/models/segformer/modeling_segformer.py:550, in SegformerModel.forward(self, pixel_values, output_attentions, output_hidden_states, return_dict)
    545 output_hidden_states = (
    546     output_hidden_states if output_hidden_states is not None else self.config.output_hidden_states
    547 )
    548 return_dict = return_dict if return_dict is not None else self.config.use_return_dict
--> 550 encoder_outputs = self.encoder(
    551     pixel_values,
    552     output_attentions=output_attentions,
    553     output_hidden_states=output_hidden_states,
    554     return_dict=return_dict,
    555 )
    556 sequence_output = encoder_outputs[0]
    558 if not return_dict:

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1527, in Module._call_impl(self, *args, **kwargs)
   1522 # If we don't have any hooks, we want to skip the rest of the logic in
   1523 # this function, and just call forward.
   1524 if not (self._backward_hooks or self._backward_pre_hooks or self._forward_hooks or self._forward_pre_hooks
   1525         or _global_backward_pre_hooks or _global_backward_hooks
   1526         or _global_forward_hooks or _global_forward_pre_hooks):
-> 1527     return forward_call(*args, **kwargs)
   1529 try:
   1530     result = None

File /usr/local/lib/python3.11/dist-packages/transformers/models/segformer/modeling_segformer.py:427, in SegformerEncoder.forward(self, pixel_values, output_attentions, output_hidden_states, return_dict)
    425 # second, send embeddings through blocks
    426 for i, blk in enumerate(block_layer):
--> 427     layer_outputs = blk(hidden_states, height, width, output_attentions)
    428     hidden_states = layer_outputs[0]
    429     if output_attentions:

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1518, in Module._wrapped_call_impl(self, *args, **kwargs)
   1516     return self._compiled_call_impl(*args, **kwargs)  # type: ignore[misc]
   1517 else:
-> 1518     return self._call_impl(*args, **kwargs)

File /usr/local/lib/python3.11/dist-packages/torch/nn/modules/module.py:1581, in Module._call_impl(self, *args, **kwargs)
   1579     hook_result = hook(self, args, kwargs, result)
   1580 else:
-> 1581     hook_result = hook(self, args, result)
   1583 if hook_result is not None:
   1584     result = hook_result

File /usr/local/lib/python3.11/dist-packages/pytorch_grad_cam/activations_and_gradients.py:24, in ActivationsAndGradients.save_activation(self, module, input, output)
     22 if self.reshape_transform is not None:
     23     activation = self.reshape_transform(activation)
---> 24 self.activations.append(activation.cpu().detach())

AttributeError: 'tuple' object has no attribute 'cpu'
`

Any ideas how to solve this issue in my case?

**Comment by Muraam-Abdel-Ghani** [comment]
> Hello,
> 
> I have faced similar problem with YOLOv7 model long ago. I would suggest you specifiy the tupel output more like using the first tuple element [0]. If I understand well as I assume, your tuple is the output of your model. You need to extract the the right tensor out of this big tuple to use it with Grad-CAM. in many cases it's as I mentioned the first element of the tuple [0].

Hello, so actually the tuple object that I'm getting the error on is the model activations, which is not something I pass to the function or extract from the model but rather it is returned within the scripts of the Grad-Cam function itself from the model. Since I am working on a cloud development space I don't have access to the installed packages so I cannot change the returned item from activations to activations[0].

**Comment by azizjadehs** [comment]
> Hello, so actually the tuple object that I'm getting the error on is the model activations, which is not something I pass to the function or extract from the model but rather it is returned within the scripts of the Grad-Cam function itself from the model. Since I am working on a cloud development space I don't have access to the installed packages so I cannot change the returned item from activations to activations[0].

I would suggest taking a look at the main code I made to use Grad-CAM on my YOLOv7, where I also made the code to extract only the first element of the tuple[0]. You can modify the code to load your model and weights along with the libraries you want to use.
[https://github.com/azizjadehs/YOLOv7-to-be-used-on-Grad-CAM/blob/main/src/main_code.py](url)

There is also the class I made called "Classifier_output_target" [https://github.com/azizjadehs/YOLOv7-to-be-used-on-Grad-CAM/blob/main/src/classifier_output_target.py](url) , Which specify the model output to the first element of the tuple.

Because the problem with Grad-CAM is that it assumes the model's output includes only the element needed for the gradient's calculation, however in your case and my case the models gives a whole tuple instead of only the needed tensor.
