### ISSUE TITLE
Float 16 not supported by EigenCAM methods (TypeError: array type float16 is unsupported in linalg )

### ISSUE THREAD

**Issue by Ryan37342342** [jacobgil/pytorch-grad-cam#442]
Hi I am getting this error when I load my model in float16 (model.half()) to use on the GPU, works fine when I use model.float(), is there a another work around for this ? Note I have cast the tensor to a float 32 outside of the model before I pass it into cam. I am using a yolov5 variant as the model.  

Traceback (most recent call last):
line 146, in <module>
    main()
  File "/home/lonrix/smapping/EigenCam/maptest.py", line 111, in main
    grayscale_cam = cam(tensor, class_id)[0, :, :]
                    ^^^^^^^^^^^^^^^^^^^^^
  File "/home/lonrix/anaconda3/envs/mapping/lib/python3.11/site-packages/pytorch_grad_cam/base_cam.py", line 188, in __call__
    return self.forward(input_tensor,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lonrix/anaconda3/envs/mapping/lib/python3.11/site-packages/pytorch_grad_cam/base_cam.py", line 95, in forward
    cam_per_layer = self.compute_cam_per_layer(input_tensor,
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lonrix/anaconda3/envs/mapping/lib/python3.11/site-packages/pytorch_grad_cam/base_cam.py", line 127, in compute_cam_per_layer
    cam = self.get_cam_image(input_tensor,
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lonrix/anaconda3/envs/mapping/lib/python3.11/site-packages/pytorch_grad_cam/eigen_cam.py", line 23, in get_cam_image
    return get_2d_projection(activations)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lonrix/anaconda3/envs/mapping/lib/python3.11/site-packages/pytorch_grad_cam/utils/svd_on_activations.py", line 15, in get_2d_projection
    U, S, VT = np.linalg.svd(reshaped_activations, full_matrices=True)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lonrix/anaconda3/envs/mapping/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 1663, in svd
    t, result_t = _commonType(a)
                  ^^^^^^^^^^^^^^
  File "/home/lonrix/anaconda3/envs/mapping/lib/python3.11/site-packages/numpy/linalg/linalg.py", line 173, in _commonType
    raise TypeError("array type %s is unsupported in linalg" %
TypeError: array type float16 is unsupported in linalg

**Comment by Ryan37342342** [comment]
I have solved by running the whole program under
 with torch.autocast(device_type="cuda",dtype=torch.float16 ):
